// ETH32 - an Enemy Territory cheat for windows
// Copyright (c) 2007 eth32 team
// www.cheatersutopia.com & www.nixcoders.org

#pragma once
#define MAX_SETTING_VALUES	20

typedef enum {
	SETTING_INT,
	SETTING_FLOAT,
	SETTING_BOOL,
	SETTING_VEC3,
	SETTING_VEC4,
	SETTING_BYTE3,
	SETTING_STRING,
	MAX_SETTINGS
} settingtype_t;

typedef struct settingvalue_s {
	float value;
	char *text;
} settingvalue_t;

typedef struct settingdef_s {
	char *name;
	char *defaultValue;
	settingtype_t type;
	void *target;
	char *description;
	float min, max;
	settingvalue_t values[MAX_SETTING_VALUES];
} settingdef_t;

const static settingdef_t settingsDefs[] =
{
	// Name				Default			Type				Target
	//	Description
	//	Min / Max
	//	  Value				TextValue
	{ "champlayer",		"0",			SETTING_INT,		(void*)&eth32.settings.chamsPlayer,
		"set the style of chams to be applied to players",
		CHAMS_OFF, MAX_CHAMS-1,
		{
			{ (int)CHAMS_OFF,		"off" },
			{ (int)CHAMS_KERAMIC,		"keramic" },
			{ (int)CHAMS_CRYSTAL,		"crystal" },
			{ (int)CHAMS_GLOW,		"glow" },
			{ (int)CHAMS_FLAME,		"flame" },
			{ (int)CHAMS_SOLIDA,		"solid.A" },
			{ (int)CHAMS_SOLIDB,		"solid.B" },
			{ (int)CHAMS_QUADA,		"quad.a" },
			{ (int)CHAMS_QUADB,		"quad.b" },
			{ (int)CHAMS_QUADC,		"quad.c" },
			{ (int)CHAMS_QUADD,		"quad.d" },
			{ (int)CHAMS_MATRIX,		"matrix" },
			{ (int)CHAMS_THERMAL,		"thermal" },
			{ (int)CHAMS_PLASTIC,		"plastic" },
			{ (int)CHAMS_PLASMA,		"plasma" },
			{ (int)CHAMS_TEST,		"test" },
		},
	},
	{ "chamweapon",		"1",			SETTING_INT,		(void*)&eth32.settings.chamsWeapon,
		"set the style of chams to be applied to weapons",
		CHAMS_OFF, MAX_CHAMS-1,
		{
			{ (int)CHAMS_KERAMIC,		"keramic" },
			{ (int)CHAMS_CRYSTAL,		"crystal" },
			{ (int)CHAMS_SOLIDA,		"solid.A" },
			{ (int)CHAMS_SOLIDB,		"solid.B" },
			{ (int)CHAMS_QUADA,		"quad.a" },
			{ (int)CHAMS_QUADB,		"quad.b" },
			{ (int)CHAMS_QUADC,		"quad.c" },
			{ (int)CHAMS_QUADD,		"quad.d" },
			{ (int)CHAMS_MATRIX,		"matrix" },
			{ (int)CHAMS_THERMAL,		"thermal" },
			{ (int)CHAMS_PLASTIC,		"plastic" },
			{ (int)CHAMS_PLASMA,		"plasma" },
			{ (int)CHAMS_TEST,		"test" },
		},
	},
	{ "ourweapcham",	"false",		SETTING_BOOL,		(void*)&eth32.settings.chamsOurWeapon,
		"apply weapon chams to our own weapon",
	},
	{ "outline",	"true",		SETTING_BOOL,		(void*)&eth32.settings.hasOutlineShader,
		"outline chams",
	},
	{ "outlineb",	"true",		SETTING_BOOL,		(void*)&eth32.settings.hasOutlineShaderB,
		"outline chams",
	},
	{ "espname",		"true",			SETTING_BOOL,		(void*)&eth32.settings.espName,
		"display player names above their heads",
	},
	{ "wallhack",		"true",			SETTING_BOOL,		(void*)&eth32.settings.wallhack,
		"view players and items through walls",
	},
	{ "wallhackdist",	"20000.0",		SETTING_FLOAT,		(void*)&eth32.settings.wallhackDistance,
		"distance over which to enable wallhack for players",
		0, 20000,
	},
	{ "wallhackdist_enable",	"false",	SETTING_BOOL,	(void*)&eth32.settings.doDistWallhack,
		"enable distance sensitive wallhack",
	},
	{ "blackout",		"false",		SETTING_BOOL,		(void*)&eth32.settings.blackout,
		"display the blackout around scoped weapons",
	},
	{ "specunlock",        "true",        SETTING_BOOL,        (void*)&eth32.settings.specLockRemove, 
		"removes spectator locking (black screen)", 
	},
	{ "weapzoom",		"false",		SETTING_BOOL,		(void*)&eth32.settings.weaponZoom,
		"toggle weapon zoom for scoped weapons",
	},
	{ "scopedspeed",	"1.0",			SETTING_FLOAT,		(void*)&eth32.settings.scopedTurnSpeed,
		"determines turning speed while scoped, (normal unscoped speed = 1.0)",
		0.1, 1.0,
	},
	{ "smoketransp",	"0",			SETTING_INT,		(void*)&eth32.settings.smoketrnsp,
		"set the transparency of smoke",
		0,	100,
	},
	{ "respawntimers",	"true",			SETTING_BOOL,		(void*)&eth32.settings.respawnTimers,
		"display friendly and enemy respawn times",
	},
	{ "autotapout",		"false",		SETTING_BOOL,		(void*)&eth32.settings.autoTapout,
		"when killed, auto-tapout and sends you instantly to the reinforcements queue",
	},
	{ "nameclick",		"false",		SETTING_BOOL,		(void*)&eth32.settings.nameClick,
		"allows you to click a name in chat window to setup a private message",
	},
 	{ "speclist",		"true",		SETTING_BOOL,		(void*)&eth32.settings.getSpeclist,
		 "show who is spectating you",
 	},
 	{ "specserv",		"",				SETTING_STRING,		(void*)eth32.settings.specServer,
 		"alternate server IP/port (in case of troublesome BNC)",
 	},
	{ "aimmode",		"1",			SETTING_INT,		(void*)&eth32.settings.aimMode,
		"master aimbot mode",
		AIMMODE_OFF, AIMMODE_MAX-1,
		{
			{ (int)AIMMODE_OFF,		"off" },
			{ (int)AIMMODE_NORMAL,	"normal" },
			{ (int)AIMMODE_HUMAN, 	"human" },
		},
	},
	{ "humanvalue",	"0.500",			SETTING_FLOAT,		(void*)&eth32.settings.humanvalue,
		"human aim value",
		0, 1,
	},
	{ "divmin",	"1",			SETTING_FLOAT,		(void*)&eth32.settings.divmin,
		"div min human aim value",
		0, 10,
	},
	{ "divmax",	"2",			SETTING_FLOAT,		(void*)&eth32.settings.divmax,
		"div max human aim value",
		0, 10,
	},
	{ "yspeed",	"0.90",			SETTING_FLOAT,		(void*)&eth32.settings.yspeed,
		"vertical speed human aim value",
		0, 1,
	},
	{ "xspeed",	"0.85",			SETTING_FLOAT,		(void*)&eth32.settings.xspeed,
		"horizontal speed human aim value",
		0, 1,
	},
	{ "aimtype",		"1",			SETTING_INT,		(void*)&eth32.settings.aimType,
		"determines when the aimbot will activate",
		AIM_OFF, AIM_MAX-1,
		{
			{ (int)AIM_OFF,		"off" },
			{ (int)AIM_ON_FIRE,	"onfire" },
			{ (int)AIM_ON_BUTTON, 	"onbutton" },
			{ (int)AIM_ALWAYS,	"always" },
			{ (int)AIM_TRIGGER,	"trigger" },	
		},
	},
	{ "aimsort",		"1",			SETTING_INT,		(void*)&eth32.settings.aimSort,
		"sets type of sort to be used with valid targets",
		SORT_OFF, SORT_MAX-1,
		{
			{ (int)SORT_OFF,		"off" },
			{ (int)SORT_DISTANCE,		"distance" },
			{ (int)SORT_CROSSHAIR,		"crosshair" },
			{ (int)SORT_TARGETING,		"targeting" },
		    	{ (int)SORT_MULTI,   		"Multi" },
			{ (int)SORT_THREAT,		"Threat" },
		    	{ (int)SORT_DISTHP,   		"Distance & HP" },
			{ (int)SORT_DISTTHREAT,   	"Distance & Threat" },
		},
	},
	{ "autofire",		"false",		SETTING_BOOL,		(void*)&eth32.settings.autofire,
		"aimbot will fire for you when target available\n   (note: autofire must be turned on per weapon as well)",
	},
	{ "locktarget",		"false",		SETTING_BOOL,		(void*)&eth32.settings.lockTarget,
		"once a target is aquired, aimbot will stay on this target while it remains visible",
	},
	{ "headbody",		"4",			SETTING_INT,		(void*)&eth32.settings.headbody,
		"determines if the aimbot uses the head or body and which order",
		0, AP_MAX-1,
		{
			{ (int)BODY_ONLY,		"bodyonly" },
			{ (int)HEAD_ONLY,		"headonly" },
			{ (int)BODY_HEAD,		"bodyfirst" },
			{ (int)HEAD_BODY,		"headfirst" },
			{ (int)HEAD_PRIORITY,		"headpriority" },
		},
	},
	{ "atkvalid",		"false",		SETTING_BOOL,		(void*)&eth32.settings.atkValidate,
		"inhibits firing, even manually, until a valid target is visible",
	},
	{ "hitbox",			"1",			SETTING_INT,		(void*)&eth32.settings.hitboxType,
		"set the hitbox style to use for aimbot",
		HITBOX_OFF, HITBOX_MAX-2,
		{
			{ (int)HITBOX_ETMAIN,	"etmain" },
			{ (int)HITBOX_ETPUB,	"etpub" },
			{ (int)HITBOX_ETPRO,	"etpro" },
			{ (int)HITBOX_GENERIC,	"generic" },
			{ (int)HITBOX_CUSTOM,	"custom" },
		},
	},
	{ "trace",			"0",			SETTING_INT,		(void*)&eth32.settings.traceType,
		"set the style of trace used to determine if a target is visible",
		0, TRACE_MAX-1,
		{
			{ (int)TRACE_CENTER,		"center" },
			{ (int)TRACE_RANDOM_VOLUME,		"randvolume" },
			{ (int)TRACE_RANDOM_SURFACE,	"randsurface" },
            { (int)TRACE_CAPSULE_VOLUME,	   "capvolume" },
            { (int)TRACE_CAPSULE_SURFACE,		"capsurface" },
		},
	},
	{ "trans_console",	"false",	SETTING_BOOL, (void*)&eth32.settings.transparantConsole,
		"make the console transparent so you can see whats going on :)"
	},
	{ "valgrentrajectory", "true",		SETTING_BOOL, (void*)&eth32.settings.valGrenTrajectory,
		"make additional calculations to make sure the grenade doesn't hit anything",
	},
	{ "valrifletrajectory", "true",		SETTING_BOOL, (void*)&eth32.settings.valRifleTrajectory,
		"make additional calculations to make sure the riflegrenade doesn't hit anything",
	},
	{ "grenadeZ",	"0.0",				SETTING_FLOAT,	(void*)&eth32.settings.grenadeZ,
		"z correction for grenade aimpoint",
	},
	{ "riflenadeZ",	"0.0",			SETTING_FLOAT,	(void*)&eth32.settings.riflenadeZ,
		"z correction for rifle grenade aimpoint",
	},
	{ "grenadeautofire", "false",	SETTING_BOOL,	(void*)&eth32.settings.grenadeAutoFire,
		"auto-fire grenade so it will explode right on contact",
	},
	{ "rifleautofire", "false",		SETTING_BOOL,	(void*)&eth32.settings.rifleAutoFire,
		"auto-fire riflegrenade as soon as we have a firing solution",
	},
	{ "grenadetracer", "true",	SETTING_BOOL,				(void*)&eth32.settings.grenadeTracer,
		"shows trajectory of the grenade",
	},
	{ "rifletracer", "true",	SETTING_BOOL,				(void*)&eth32.settings.rifleTracer,
		"shows trajectory of the rifle grenade",
	},
	{ "grensenslock", "false",	SETTING_BOOL,				(void*)&eth32.settings.grenadeSenslock,
		"locks view if there is a valid firing solution",
	},
	{ "grenadebot", "true",	SETTING_BOOL,				(void*)&eth32.settings.grenadeBot,
		"toggles the grenade aimbot",
	},
	{ "riflebot", "true",	SETTING_BOOL,				(void*)&eth32.settings.rifleBot,
		"toggles the riflegrenade aimbot",
	},
	{ "grenblockfire", "true",	SETTING_BOOL,				(void*)&eth32.settings.grenadeBlockFire,
		"blocks firing grenades by accident if there isn't a firing solution",
	},
	{ "grenfiredelay",	"0",			SETTING_INT,		(void*)&eth32.settings.grenadeFireDelay,
		"the time it takes when releasing fire button and the grenade is launched (leave if you dont know what you're doing)",
		0, 1000,
	},
	{ "radiusdamage_enable", "true",	SETTING_BOOL,				(void*)&eth32.settings.ballisticRadiusDamage,
		"if target is not visible, try a point within the grenade's blast radius",
	},
	{ "radiusdamage",	"265.0",			SETTING_FLOAT,		(void*)&eth32.settings.radiusDamage,
		"the grenade blast radius to use",
		30, 1000,
	},
	{ "grenpredict",	"1",			SETTING_INT,		(void*)&eth32.settings.ballisticPredict,
		"predict targets for grenade aimbot",
		0, RF_PREDICT_MAX-1,
		{
				{ (int)RF_PREDICT_OFF, "off" },
				{ (int)RF_PREDICT_LINEAR, "linear" },
				{ (int)RF_PREDICT_LINEAR2, "linear/2" },
				{ (int)RF_PREDICT_AVG, "average pos" },
				{ (int)RF_PREDICT_SMART, "smart" },
		}
	},
	{ "grenautotarg",	"false",			SETTING_BOOL,		(void*)&eth32.settings.autoGrenTargets,
		"automatically selects grenade targets based on crosshair distance",
	},
	{ "grenblockfire", "true",	SETTING_BOOL,				(void*)&eth32.settings.grenadeBlockFire,
		"blocks firing grenades by accident if there isn't a firing solution",
	},
	{ "fov",			"360.0",		SETTING_FLOAT,		(void*)&eth32.settings.fov,
		"set the field of vision that the aimbot can select targets from",
		0, 360,
	},
    { "aimprotect",		"2",			SETTING_INT,		(void*)&eth32.settings.aimprotect,
		"turn off aimbot when people are watching",
		0, PROTECT_MAX-2,
		{
			{ (int)PROTECT_OFF,	"off" },
			{ (int)PROTECT_SPECS,	"specs" },
			{ (int)PROTECT_ALL,	"all" },
		},
	},
	{ "multibounce",	"true",		SETTING_BOOL,		(void*)&eth32.settings.allowMultiBounce,
		"use extra CPU to calculate secondary trajectories with multiple bounces off walls",
	},
	{ "predtarget",		"0.0",			SETTING_FLOAT,		(void*)&eth32.settings.predTarget,
		"set amount of prediction to be applied to targets",
		-1.0, 1.0,
	},
	{ "predtest",  "0.0",   SETTING_FLOAT,  (void*)&eth32.settings.predTest,
        "set amount to selfprediction test",
        -10, 10,
    	},
	{ "bodysize",		"34",			SETTING_FLOAT,		(void*)&eth32.settings.bodybox,
		"body hitbox size",
		0, 50,
	},
	{ "corr range",		"10000",		SETTING_FLOAT,			(void*)&eth32.settings.RangE,
		"vecs correction based on distance",
		0, 10000,
	},
		{ "corrrange",		"10000",		SETTING_FLOAT,		(void*)&eth32.settings.RangE,
		"maximum distance for auto corrections",
		0, 10000,
	},
	{ "autovecxstandclose",	"0.495",			SETTING_FLOAT,	(void*)&eth32.settings.vecstandcloseX,
		"correction amount for X vec, close range (standing and running)",
		-10.0, 10.0,
	},
	{ "autovecxstandfar",	"0.125",			SETTING_FLOAT,	(void*)&eth32.settings.vecstandfarX,
		"correction amount for X vec, far range (standing and running)",
		-10.0, 10.0,
	},
	{ "autovecxcrouchclose",	"0.370",		SETTING_FLOAT,	(void*)&eth32.settings.veccrouchcloseX,
		"correction amount for X vec, close range (crouching and crawling)",
		-10.0, 10.0,
	},
	{ "autovecxcrouchfar",	"1.480",			SETTING_FLOAT,	(void*)&eth32.settings.veccrouchfarX,
		"correction amount for X vec, far range (crouching and crawling)",
		-10.0, 10.0,
	},

	{ "autovecystandclose",	"-0.125",			SETTING_FLOAT,	(void*)&eth32.settings.vecstandcloseY,
		"correction amount for Y vec, close range (standing and running)",
		-10.0, 10.0,
	},
	{ "autovecystandfar",	"-0.125",			SETTING_FLOAT,	(void*)&eth32.settings.vecstandfarY,
		"correction amount for Y vec, far range (standing and running)",
		-10.0, 10.0,
	},
	{ "autovecycrouchclose",	"0.125",		SETTING_FLOAT,	(void*)&eth32.settings.veccrouchcloseY,
		"correction amount for Y vec, close range (crouching and crawling)",
		-10.0, 10.0,
	},
	{ "autovecycrouchfar",	"-0.245",			SETTING_FLOAT,	(void*)&eth32.settings.veccrouchfarY,
		"correction amount for Y vec, close range (crouching and crawling)",
		-10.0, 10.0,
	},
	{ "autoveczstandclose",	"6.666",			SETTING_FLOAT,	(void*)&eth32.settings.vecstandcloseZ,
		"correction amount for Z vec, close range (standing and running)",
		-10.0, 10.0,
	},
	{ "autoveczstandfar",	"1.000",			SETTING_FLOAT,	(void*)&eth32.settings.vecstandfarZ,
		"correction amount for Z vec, far range (standing and running)",
		-10.0, 10.0,
	},
	{ "autoveczcrouchclose",	"6.540",		SETTING_FLOAT,	(void*)&eth32.settings.veccrouchcloseZ,
		"correction amount for Z vec, close range (crouching and crawling)",
		-10.0, 10.0,
	},
	{ "autoveczcrouchfar",	"1.000",			SETTING_FLOAT,	(void*)&eth32.settings.veccrouchfarZ,
		"correction amount for Z vec, far range (crouching and crawling)",
		-10.0, 10.0,
	},
	{ "autovecxproneclose",	"0.535",			SETTING_FLOAT,	(void*)&eth32.settings.vecpronecloseX,
		"correction amount for X vec, close range (prone)",
		-10.0, 10.0,
	},
	{ "autovecxpronefar",	"0.535",			SETTING_FLOAT,	(void*)&eth32.settings.vecpronefarX,
		"correction amount for X vec, far range (prone)",
		-10.0, 10.0,
	},
	{ "autovecyproneclose",	"0.000",			SETTING_FLOAT,	(void*)&eth32.settings.vecpronecloseY,
		"correction amount for Y vec, close range (prone)",
		-10.0, 10.0,
	},
	{ "autovecypronefar",	"0.000",			SETTING_FLOAT,	(void*)&eth32.settings.vecpronefarY,
		"correction amount for Y vec, far range (prone)",
		-10.0, 10.0,
	},
	{ "autoveczproneclose",	"6.520",			SETTING_FLOAT,	(void*)&eth32.settings.vecpronecloseZ,
		"correction amount for Z vec, close range (prone)",
		-10.0, 10.0,
	},
	{ "autoveczpronefar",	"6.520",			SETTING_FLOAT,	(void*)&eth32.settings.vecpronefarZ,
		"correction amount for Z vec, far range (prone)",
		-10.0, 10.0,
	},
	{ "autohitbox",	     "true",	       SETTING_BOOL,			(void*)&eth32.settings.autoBoxSize,
		"auto head hitbox size",
	},
	{ "autohitboxsfar",	   	"8",	    SETTING_FLOAT,			(void*)&eth32.settings.farBoxSize,
		"head hitbox size (far distance)",
		0, 20,
	},
	{ "autohitboxsclose",	   	"11",	    SETTING_FLOAT,			(void*)&eth32.settings.closeBoxSize,
		"head hitbox size (close distance)",
		0, 20,
	},
	{ "autohitboxrange",	   	"18000.0",	    SETTING_FLOAT,			(void*)&eth32.settings.rangeBoxSize,
		"maximum range for auto headhitbox size",
		0, 18000,
	},
	{ "snapdelay",	     "true",	       SETTING_BOOL,			(void*)&eth32.settings.snapDelay,
		"snap delay prediction",
	},
	{ "delaycorr",	     "true",	       SETTING_BOOL,			(void*)&eth32.settings.delaycorr,
		"auto weapon shooting delay (useful for long distances)",
	},
	{ "delayclose",	   	"0.0",	    SETTING_FLOAT,			(void*)&eth32.settings.delayclose,
		"weapon shooting delay in close distance",
		0.00, 64.00,
	},
	{ "delayfar",	   	"0.0",	    SETTING_FLOAT,			(void*)&eth32.settings.delayfar,
		"weapon shooting delay in far distance",
		0.00, 64.00,
	},
	{ "delayrange",	   	"18000.0",	    SETTING_FLOAT,			(void*)&eth32.settings.delayrange,
		"maximum range for delay correction",
		0, 18000,
	},
	{ "pointsclose",	   	"100.0",	    SETTING_FLOAT,	(void*)&eth32.settings.pointsclose,
		"max autopoints in close distance",
		0, 100,
	},
	{ "pointsfar",	   	"1.0",	    SETTING_FLOAT,	(void*)&eth32.settings.pointsfar,
		"max autopoints in far distance",
		0, 100,
	},
	{ "predself_type",	"1",			SETTING_INT,		(void*)&eth32.settings.predSelfType,
		"set the type of self prediction to apply",
		0, SPR_MAX-1,
	},
	{ "dynamicHitbox",	"0.0",			SETTING_FLOAT,		(void*)&eth32.settings.dynamicHitboxScale,
		"set how much a hitbox will scale based on player movement",
		0, 10,
	},
	{ "killspam",		"false",		SETTING_BOOL,		(void*)&eth32.settings.killSpam,
		"enable automated message when a target is killed",
	},
	{ "multikillspam",	"false",		SETTING_BOOL,		(void*)&eth32.settings.multikillSpam,
		"enable automated message when making a multikill",
	},
	{ "deathspam",		"false",		SETTING_BOOL,		(void*)&eth32.settings.deathSpam,
		"enable automated message when you die",
	},
	{ "suicidespam",	"false",		SETTING_BOOL,		(void*)&eth32.settings.suicideSpam,
		"enable automated PM when someone commits suicide",
	},
	{ "selfkillspam",	"false",		SETTING_BOOL,		(void*)&eth32.settings.selfkillSpam,
		"enable automated message when you /kill or suicide",
	},
	{ "pmkillspam",		"false",		SETTING_BOOL,		(void*)&eth32.settings.pmKillspam,
		"make PM killspam to victim instead of global chat",
	},
	{ "killspamtype",	"0",			SETTING_INT,		(void*)&eth32.settings.KillspamType,
		"make killspam for everyone or only selected players",
		0, KILLSPAM_MAX-1,
		{
			{ (int)KILLSPAM_ALL,		"all" },
			{ (int)KILLSPAM_SELECTED,	"selected" },
		},
	},
	{ "killsounds",		"true",		SETTING_BOOL,		(void*)&eth32.settings.killSounds,
		"enables sounds to be played when a player is killed",
	},
	{ "hitsounds",		"true",		SETTING_BOOL,		(void*)&eth32.settings.hitsounds,
		"enable sounds when you do damage to another player",
	},
	{ "hitsounds2",		"true",		SETTING_BOOL,		(void*)&eth32.settings.hitsounds2,
		"enable sounds when you do damage to another player",
	},
	{ "hitsounds3",		"true",		SETTING_BOOL,		(void*)&eth32.settings.hitsounds3,
		"enable sounds when you do damage to another player",
	},
	{ "mkillresettime",	"3000",			SETTING_FLOAT,		(void*)&eth32.settings.mkResetTime,
		"period in milliseconds after which multikill sound gets reset",
		0, 10000,
	},
	{ "hqsounds", 		"true",			SETTING_BOOL,		(void*)&eth32.settings.hqSounds,
		"play HQ sounds (like 'Dynamite Planted')",
	},
	{ "puresounds",		"false",		SETTING_BOOL,		(void*)&eth32.settings.pureSounds,
		"only play pure sounds, this will disable anoying custom voicechats",
	},
	{ "radarrange",		"3000.0",		SETTING_FLOAT,		(void*)&eth32.settings.radarRange,
		"set the range of the radar window",
		100, 18000,
	},
	{ "xhairsize",	"20",			SETTING_FLOAT,		(void*)&eth32.settings.crossSize,
		"sets custom crosshair size",
		0, 100,
	},
	{ "xhairthick",	"1",			SETTING_FLOAT,		(void*)&eth32.settings.crossThick,
		"sets custom crosshair thickness",
		0, 10,
	},
	{ "xhairtype",		"0",			SETTING_INT,		(void*)&eth32.settings.customXhair,
		"sets the custom crosshair type",
		XHAIR_OFF, XHAIR_MAX-1,
		{
			{ (int)XHAIR_OFF,	"off" },
			{ (int)XHAIR_SNIPER,	"Sniper" },
			{ (int)XHAIR_CROSS, 	"Open Cross" },
			{ (int)XHAIR_CROSS2,	"Closed Cross" },
			{ (int)XHAIR_DOT,	"Dot" },
			{ (int)XHAIR_LINE,	"Line" },
		},
	},
	{ "removefoliage",		"true",		SETTING_BOOL,		(void*)&eth32.settings.removeFoliage,
		"completely removes the foliage (trees, bushes, etc)",
	},
	{ "customskies",		"true",		SETTING_BOOL,		(void*)&eth32.settings.customSkies,
		"enables cusom skies for maps",
	},
	{ "xhairinfo",		"false",			SETTING_BOOL,		(void*)&eth32.settings.xhairInfo,
		"enable the crosshair info window",
	},
	{ "xhairinfotime",	"300",			SETTING_INT,		(void*)&eth32.settings.xhairInfoTime,
		"set how long crosshair info window will stay up (in msec)",
		0, 3000,
	},
	{ "colorteam",		"0 255 0",		SETTING_BYTE3,		(void*)eth32.settings.colorTeam,
		"set the color of team chams",
	},
	{ "colorteamout",		"0 0 255",		SETTING_BYTE3,		(void*)eth32.settings.colorTeamOut,
		"set the color of team outline",
	},
	{ "colorteamhid",	"0 100 0",		SETTING_BYTE3,		(void*)eth32.settings.colorTeamHidden,
		"set the color of team chams when hidden",
	},
	{ "colorenemy",		"255 0 0",		SETTING_BYTE3,		(void*)eth32.settings.colorEnemy,
		"set the color of enemy chams",
	},
	{ "colorenemyout",		"255 0 255",		SETTING_BYTE3,		(void*)eth32.settings.colorEnemyOut,
		"set the color of enemy outline",
	},
	{ "colorenemyhid",	"100 0 0",		SETTING_BYTE3,		(void*)eth32.settings.colorEnemyHidden,
		"set the color of enemy chams when hidden",
	},
	{ "colorinvuln",	"255 255 0",	SETTING_BYTE3,		(void*)eth32.settings.colorInvulnerable,
		"set the color of player chams when they are invulnerable",
	},
	{ "colorteamweap",	"255 0 255",	SETTING_BYTE3,		(void*)eth32.settings.colorTeamWeapon,
		"set the color of team weapons",
	},
	{ "colorenemyweap", "255 255 0",	SETTING_BYTE3,		(void*)eth32.settings.colorEnemyWeapon,
		"set the color of enemy weapons",
	},
	{ "colorhealth",	"0 0 255",		SETTING_BYTE3,		(void*)eth32.settings.colorHealth,
		"set the color of health kits",
	},
	{ "colorammo",		"0 70 255",		SETTING_BYTE3,		(void*)eth32.settings.colorAmmo,
		"set the color of ammo boxes",
	},
	// hitbox drawing, custom tracers
	{ "headhitbox",		"true",			SETTING_BOOL,		(void*)&eth32.settings.drawHeadHitbox,
		"enable head hitbox drawing",
	},
	{ "headaxes",		"true",		SETTING_BOOL,		(void*)&eth32.settings.drawHeadAxes,
		"enable hitbox axis drawing",
	},
	{ "bodyhitbox",		"true",		SETTING_BOOL,		(void*)&eth32.settings.drawBodyHitbox,
		"enable body hitbox drawing",
	},
	{ "bulletrail",		"false",		SETTING_BOOL,		(void*)&eth32.settings.drawBulletRail,
		"enable bullet tracers",
	},
	{ "railwallhack",	"true",		SETTING_BOOL,		(void*)&eth32.settings.railWallhack,
		"see hitboxes and bullet tracers through walls",
	},
	{ "colorheadhb",	"0 1 0",		SETTING_VEC3,		(void*)eth32.settings.colorHeadHitbox,
		"set the color of the head hitbox",
	},
	{ "colorbodyhb",	"0 1 0",		SETTING_VEC3,		(void*)eth32.settings.colorBodyHitbox,
		"set the color of the body hitbox",
	},
	{ "colorbulletrail",	"1 0 0",		SETTING_VEC3,		(void*)eth32.settings.colorBulletRail,
		"set the color of bullet tracers",
	},
	{ "colorxaxis",		"1 0 0",		SETTING_VEC3,		(void*)eth32.settings.colorXAxis,
		"set the color of hitbox x-axis",
	},
	{ "coloryaxis",		"0 1 0",		SETTING_VEC3,		(void*)eth32.settings.colorYAxis,
		"set the color of hitbox y-axis",
	},
	{ "colorzaxis",		"0 0 1",		SETTING_VEC3,		(void*)eth32.settings.colorZAxis,
		"set the color of hitbox z-axis",
	},
	{ "headhbtime",		"40",			SETTING_INT,		(void*)&eth32.settings.headRailTime,
		"set head hitbox stay time (in msec)",
		0, 1000,
	},
	{ "bodyhbtime",		"40",			SETTING_INT,		(void*)&eth32.settings.bodyRailTime,
		"set body hitbox stay time (in msec)",
		0, 1000,
	},
	{ "bulletrailtime",	"40",			SETTING_INT,		(void*)&eth32.settings.bulletRailTime,
		"set bullet tracer stay time (in msec)",
		0, 1000,
	},

	{ "etproOs",		"true",			SETTING_BOOL,		(void*)&eth32.settings.etproOs,
		"enable etpro os spoofing",
	},
	{ "pk3name",		"eth32_public.pk3",	SETTING_STRING,		(void*)eth32.settings.pk3file,
		"the main eth32 pk3 file name",
	},
	{ "etproGuid",		"0",			SETTING_STRING,		(void*)eth32.settings.etproGuid,
		"set your custom etpro GUID",
	},
	{ "jaymac",		"UNKNOWN",				SETTING_STRING,		(void*)eth32.settings.jayMac,
		"set your custom jaymod MAC address (prevents bans based on MAC)",
	},
	{ "autopoints",		"low",			SETTING_INT,		(void*)&eth32.settings.autoPoints,
		"set automatic generation of multi aimpoints",
		0, AUTOPT_MAX-1,
		{
			{ (int)AUTOPT_OFF,	"off" },
			{ (int)AUTOPT_LOW,	"low" },
			{ (int)AUTOPT_HIGH,	"high" },
		},
	},
	{ "autocrouch",		"false",		SETTING_BOOL,		(void*)&eth32.settings.autoCrouch,
		"enable auto crouching when target is visible",
	},

	// view values
	{ "vw_origviewvalues",	"false",		SETTING_BOOL,		(void*)&eth32.settings.origViewValues,
		"enable unmodified view calculations",
	},
	{ "vw_interpolatedps",	"true",			SETTING_BOOL,		(void*)&eth32.settings.interpolatedPs,
		"enable interpolated playerstate",
	},
	{ "vw_thirdperson",	"false",		SETTING_BOOL,		(void*)&eth32.settings.thirdPerson,
		"enable third person view",
	},
	{ "vw_damagefeedback",	"false",		SETTING_BOOL,		(void*)&eth32.settings.dmgFeedback,
		"enable damage feedback",
	},

	{ "preaim",		"false",		SETTING_BOOL,			(void*)&eth32.settings.preAim,
		"preaim targets",
	},
	{ "preaimtime",		"150.0",		SETTING_FLOAT,			(void*)&eth32.settings.preAimTime,
		"preaim time - higher is earlier aiming",
		0, 5000,
	},

	{ "preshoot",		"false",		SETTING_BOOL,			(void*)&eth32.settings.preShoot,
		"pre-shoot at targets before they are logically visible",
	},
	{ "preshoottime",	"75.0",			SETTING_FLOAT,			(void*)&eth32.settings.preShootTime,
		"preshoot time - higher means earlier shot (and higher chance of miss)",
		0, 5000,
	},
	{ "spread",	"225.0",			SETTING_FLOAT,			(void*)&eth32.settings.spread,
		"weapon spread test",
		0, 400,
	},
	// custom hitbox
	{ "hb_stand",		"0 0 0",		SETTING_VEC3,		(void*)Aimbot.customHitbox.stand_offset,
		"set the hitbox center point for a standing player",
	},
	{ "hb_crouch",		"0 0 0",		SETTING_VEC3,		(void*)Aimbot.customHitbox.crouch_offset,
		"set the hitbox center point for a crouching player",
	},
	{ "hb_prone",		"0 0 0",		SETTING_VEC3,		(void*)Aimbot.customHitbox.prone_offset,
		"set the hitbox center point for a prone player",
	},
 	{ "hb_run",		"0 0 0",		SETTING_VEC3,		(void*)Aimbot.customHitbox.stand_offset_moving,
		"set the hitbox center point for a running player",
	},
	{ "hb_crawl",		"0 0 0",		SETTING_VEC3,		(void*)Aimbot.customHitbox.crouch_offset_moving,
		"set the hitbox center point for a crawling player",
	},
	{ "hb_size",		"0 0 0",		SETTING_VEC3,		(void*)Aimbot.customHitbox.size,
		"set the size of head hitbox (length, width, height)",
	},
	{ "autoheadsmg",	 "true",		SETTING_BOOL,			(void*)&eth32.settings.autoHeadsmg,
		"auto headbody priority",
	},

	{ "animcor", "0.0", SETTING_FLOAT, (void*)&eth32.settings.animCorrection,
		"animation correction for aimbot",
		-10.0, 10.0,
	},
	{ "showstats", "true", SETTING_BOOL, (void*)&eth32.settings.showStats,
		"show stats window",
	},

 	// LINUX ONLY BELOW HERE!
	{ "hackvisuals", "true", SETTING_BOOL, (void*)&eth32.settings.drawHackVisuals,
		"draw hack visuals",
	},
 	{ "pbscreenshot", "2", SETTING_INT, (void*)&eth32.settings.pbScreenShot,
		"type of PB screenshot",
  		0, PB_SS_MAX-1,
		{
			{ (int)PB_SS_NORMAL,	"normal" },
			{ (int)PB_SS_CUSTOM,	"custom" },
			{ (int)PB_SS_CLEAN,	"clean" },
		},
	},
	{ "bannerfmt", "^7Kills: ^3[k] ^0| ^7Deaths: ^3[d] ^0| ^7Accuracy: ^3[\]^n% ^0| ^7Headshots: ^3[/] &&^7Health: ^3[h] ^0| ^7Ammo: ^3[a] ^0| ^7Current Spree: ^3[S] ^0| ^7PBSSs: ^3[s]", SETTING_STRING, (void*)eth32.settings.BannerFmt,
		"banner format",
	},
	{ "bannerscale", "1.0", SETTING_FLOAT, (void*)&eth32.settings.BannerScale,
		"Banner font scale",
	},
	{ "gui_banner", "true", SETTING_BOOL, (void*)&eth32.settings.guiBanner,
		"GUI: show stats banner",
	},
	{ "gui_chat", "true", SETTING_BOOL, (void*)&eth32.settings.guiChat,
		"GUI: show eth32 chat window",
	},
	{ "gui_cp", "true", SETTING_BOOL, (void*)&eth32.settings.guiCenterPrint,
		"GUI: show centerprint banner",
	},
	{ "gui_cpanim", "true", SETTING_BOOL, (void*)&eth32.settings.guiCenterPrintAnim,
		"GUI: do centerprint animation",
	},
	{ "gui_cpscale", "1.0", SETTING_FLOAT, (void*)&eth32.settings.guiCenterPrintScale,
		"GUI: centerprint font scale",
		0.0, 10.0,
	},
	{ "gui_orig", "false", SETTING_BOOL, (void*)&eth32.settings.guiOriginal,
		"GUI: use original ET hud",
	},

	// namesteal stuff
	{ "namesteal", "false", SETTING_BOOL, (void*)&eth32.settings.doNamesteal,
		"Enable namestealing",
	},
	{ "namesteal_grace", "0", SETTING_INT, (void*)&eth32.settings.NamestealGrace,
		"Time to wait in ms to start stealing after joining a server",
		0, 10000,
	},
	{ "namesteal_mode", "2", SETTING_INT, (void*)&eth32.settings.NamestealMode,
		"Type of namestealing to do",
		0, NAMESTEAL_MAX-1,
		{
			{ (int)NAMESTEAL_TEAM,	"team" },
			{ (int)NAMESTEAL_ENEMY,	"enemy" },
			{ (int)NAMESTEAL_ALL,	"all" },
			{ (int)NAMESTEAL_FILE,	"file" },
		},
	},
	{ "namesteal_delay", "5000", SETTING_INT, (void*)&eth32.settings.NamestealDelay,
		"Time to wait between changing names (in ms)",
		0, 999999999,
	},
	{ "disguised", 		"false", SETTING_BOOL, (void *)&eth32.settings.drawDisguised,
		"draw disguised ESP on players",
	},
	{ "grenadedlight",	"true",		SETTING_BOOL,	(void*)&eth32.settings.grenadeDlight,
		"extra grenade lights inidicating blast area",
	},
	{ "mortardlight",	"true",		SETTING_BOOL,	(void*)&eth32.settings.mortarDlight,
		"extra mortar lights inidicating blast area",
	},
	{ "mortartrace",	"true",		SETTING_BOOL,	(void*)&eth32.settings.mortarTrace,
		"show mortar trace lines and impact ESP",
	},
	{ "artymarkers",	"true",		SETTING_BOOL,	(void*)&eth32.settings.artyMarkers,
		"show arty blast area lights and ESP",
	},
	{ "requeststats",	"true",		SETTING_BOOL,	(void*)&eth32.settings.requeststats,
		"continuously query the server for our stats (might cause flood kick on some servers)",
	},
};
